// Level data. Each level is 16 rows of 28 chars.
// Legend:
//   ' ' empty      '#' brick (diggable)   '@' solid slab (undiggable)
//   'H' ladder     '-' rope               'T' trap brick (false floor)
//   'X' hidden ladder (appears when all gold is collected)
//   '$' gold       'P' player spawn       'G' guard spawn

export const COLS = 28;
export const ROWS = 16;

export const LEVELS = [
  {
    name: 'FIRST JOB',
    rows: [
      '                           X',
      '                           X',
      '                           X',
      '                           X',
      '               $           X',
      '  ##########H####          X',
      '            H    -------   X',
      '            H   G  $      $X',
      '          ##H###############',
      '            H               ',
      '     $      H               ',
      '###H##########              ',
      '   H                        ',
      '   H                        ',
      ' P H    $                   ',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'THE DIG SITE',
    rows: [
      'X                           ',
      'X                           ',
      'X                           ',
      'X                           ',
      'X                           ',
      'X                           ',
      'X                           ',
      'X            $ ------       ',
      'X           #H#             ',
      'X            H              ',
      'X P    $     H        G   H ',
      '##########################H ',
      '                          H ',
      '                          H ',
      '    $    $ G   $    $     H ',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'ROPE BRIDGE',
    rows: [
      '  X                         ',
      '  X                         ',
      '  X                         ',
      '  X                         ',
      '  X                         ',
      '  X  $     ------    $  G   ',
      '########H##      ##H########',
      '        H          H        ',
      '        H          H        ',
      '  $   G H -------- H     $  ',
      'H###T####          ########H',
      'H                          H',
      'H                          H',
      'H                          H',
      'H   $         P       $    H',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'THE LONG VAULT',
    rows: [
      '                          X ',
      '                          X ',
      '                          X ',
      '                          X ',
      '                          X ',
      '                          X ',
      '                          X ',
      '                          X ',
      '   P    $      $  G       X ',
      ' H#####################   X ',
      ' H                        X ',
      ' H                        X ',
      '                G         X ',
      ' H#########@#######T####H X ',
      ' H G $     @ $   $   $  H X ',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'TWIN TOWERS',
    rows: [
      'X                           ',
      'X                           ',
      'X    $      ---- G    $     ',
      'X #H########    ########H#  ',
      'X  H                    H   ',
      'X  H        ----    $   H   ',
      'X #H####T###    ########H#  ',
      'X  H                    H   ',
      'X  H G   $       $      H   ',
      'X #H########    ##T#####H#  ',
      'X  H                    H   ',
      'X  H  $     ----   G $  H   ',
      'X #H########    ########H#  ',
      'X  H                    H   ',
      'X  H         P          H   ',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'THE UNDERCROFT',
    rows: [
      'X                           ',
      'X                           ',
      'XH                          ',
      'XH                          ',
      'XH                          ',
      'XH                          ',
      'XH                          ',
      'XH                          ',
      'XH  P     $      $  G  $   H',
      'XH###########T#############H',
      'XH                         H',
      'XH      $     $     $   G  H',
      'XH#################T#######H',
      'XH                         H',
      'XH    $     $     G     $  H',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'CHASE LOOPS',
    rows: [
      '                           X',
      '                           X',
      '                           X',
      '                           X',
      '      $    ------    $     X',
      '  ##H######      ######H## X',
      '    H                  H   X',
      '    H     $   G  $     H   X',
      '    H   #######T####   H   X',
      '    H                  H   X',
      '   $H  G            G $H   X',
      '   #####H#        #H#####  X',
      '        H          H       X',
      '        H          H       X',
      ' $      H P     G  H      $X',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'THE GAUNTLET',
    rows: [
      '             X              ',
      '             X              ',
      '             X              ',
      '             X              ',
      '             X              ',
      '      $      X     G $      ',
      '##T#H####@#######H@####H#T##',
      '    H    @       H@    H    ',
      '    H    @       H@    H    ',
      '    H    @ G$  $ H@    H    ',
      '    H    @#######H@    H    ',
      '    H    @       H@    H    ',
      '    H    @       H@    H    ',
      '    H    @       H@    H    ',
      '  $ H G  @ $ G  $H@ P  H $  ',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: 'SKY RIG',
    rows: [
      '                          X ',
      '                          X ',
      '                          X ',
      '         $ P ----  G $    X ',
      '       #H####    #H####   X ',
      '        H         H       X ',
      '        H         H       X ',
      '     G$ H---- G $ H--$    X ',
      '    #####    ######  ###### ',
      '     H         H       H    ',
      '     H         H       H    ',
      '   $ H ----  $GH ----  H$   ',
      'H######    ######    ######H',
      'H                          H',
      'H       $    G     $       H',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
  {
    name: "MOORE'S HOARD",
    rows: [
      '                           X',
      '                           X',
      '                           X',
      '       $ G         $       X',
      '    #H#####@###H@####H##   X',
      '     H     @   H@    H     X',
      '     H   $ @G$$H@G$  H     X',
      '     ##H############H##    X',
      '       H            H      X',
      '   $   H     $  G   H  $   X',
      ' H#######T########T#######HX',
      ' H                        HX',
      ' H    $              $    HX',
      ' H  ####################  HX',
      'PH      $  G  $     $     HX',
      '@@@@@@@@@@@@@@@@@@@@@@@@@@@@',
    ],
  },
];
